---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# vpfkit

<!-- badges: start -->
<!-- badges: end -->

The `vpfkit` (short for “ViroProfiler Tookit”) R package is designed for downstream analyses of [ViroProfiler](https://github.com/deng-lab/viroprofiler) results in R. It contains functions for preprocessing data generated from multiple ViroProfiler steps, and a Shiny APP called ViroProfiler-viewer for visualizing and manipulating results interactively in a web page. ViroProfiler-viewer allows users to filter viral contigs based on their length, quality, and other annotations such as taxonomy, host, and replication type. In addition, a `TreeSummarizedExperiment` object file can be generated as inputs for downstream analyses in R. In order to use the APP, please upload the `viroprofiler_output.rds` file generated by the [ViroProfiler](https://github.com/deng-lab/viroprofiler) pipeline.

## Installation

You can install vpfkit using the following command:

``` r
install.packages("remotes")
remotes::install_github("deng-lab/vpfkit")
```

Then you can load the package using:

``` r
library(vpfkit)
```

## How to run the ViroProfiler-viewer Shiny APP

ViroProfiler-viewer is included in the `vpfkit` package. You can run it using the following approaches.

### 1. Using Docker image (recommended)

``` sh
docker run --rm denglab/viroprofiler-viewer:latest R -e "options('shiny.port'=80,shiny.host='0.0.0.0');vpfkit::run_app()"
```

Then you can access the app at http://localhost. If you want to use another port, for example 8080, you can use

``` sh
docker run --rm denglab/viroprofiler-viewer:latest R -e "options('shiny.port'=80,shiny.host='0.0.0.0');vpfkit::run_app()"
```

Then you can access the app at http://localhost:8080.


### 2. Run from local R session

Open R or Rstudio, and then run the following command,

``` r
vpfkit::run_app()
```

You can also run it from the command line using the following command,

``` sh
R -e "options('shiny.port'=80,shiny.host='0.0.0.0');vpfkit::run_app()"
```

Then you can access the app at http://localhost. If you want to use another port, for example 8080, you can use

``` sh
R -e "options('shiny.port'=8080,shiny.host='0.0.0.0');vpfkit::run_app()"
```

Then you can access the app at http://localhost:8080

### 3. Online version

Due to the computation resource limitation of the cloud service, it is highly recommened to run ViroProfiler-viewer on your local computer. However, if none of the above approaches works for you, you can also use the online version of ViroProfiler-viewer at [https://deng-lab.github.io/viroprofiler-viewer](https://deng-lab.github.io/viroprofiler-viewer)
